# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Username', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
    ]
